### PR TITLE
Add remove_empty_let_in assist

### PR DESCRIPTION
**Pull request by MoritzBoehme**
Not sure if the tests are sufficient, but that is every usage that came to mind.

### CODE REVIEW

**Comment by oxalica** [comment]
Could you also add it to the docs `docs/code_actions.md`? Otherwise LGTM.

**Comment by MoritzBoehme** [comment]
Will do.

**Comment by MoritzBoehme** [comment]
Alright, I added it to the docs.

**Comment by oxalica** [comment]
Thanks!

**Pull request merged**
