### PR TITLE
Pin & use overlay rust toolchain

### PR DESCRIPTION
**Pull request by antifuchs**
This PR implements the fix I proposed for #35: It sets an explicitly-requested rustc version, which then gets used to build the package in all configurations (unless somebody were to follow an outdated `rust-overlay` input, not recommended).

I think the `devShell` logic (following whatever is on nixpkgs) isn't right with this change, I'm happy to alter it to be identical to the package-building logic.

### CODE REVIEW

**Comment by oxalica** [comment]
I'm still not convinced that we need another way to pin dependencies down. As I mentioned in #35, `flake.lock` is just for this use case. Using (maybe additional) locked nixpkgs would just pull in rustc as build-time deps and glibc as runtime deps. Switching to `rust-overlay` can only eliminate one `glibc` and you still need to download `rustc` toolchain (and auto-patch them) during the build.

I want `rust-overlay` to be able to opt-out for nixpkgs-only users. Currently it's not a hard dependency and can be removed by `follows` it to any flake.

**Comment by antifuchs** [comment]
Hm, so if the `nixpkgs` input is required to get the rust version that this program is meant to be used with, that should be documented. From what I've seen in nix flake usage around, I feel like it would be reasonable that people using this flake will want to provide their own inputs (reduce closure size, reduce the number of openssl's being pulled in) - but maybe that's so? Flakes are a bit underdocumented right now and usage is what we make of it.

**Comment by NobbZ** [comment]
The lockfile **is** the documentation. The lockfile says "its known to work like this, if you change something, you are on your own".

This is the general idea about lockfiles and not really unique to flakes…

Therefore `follows` is a nice thing sometimes, but it is simple as this: if `follows` breaks something, you can't use it.

**Comment by oxalica** [comment]
> Hm, so if the `nixpkgs` input is required to get the rust version that this program is meant to be used with, that should be documented.

The shipped one is already working. `follows` acts like `override` our dependencies. We are not responsible for installation where you replaces our dependencies to old ones, because it's simple impossible. Even with `rust-overlay`, you can still override it to one-year-ago version and break it.

Closed as actually-nothing-went-wrong.

**Comment by oxalica** [comment]
You we do want to package it with other toolchain, just call `buildRustPackage` yourself and ignore our flake.nix. It should not be too complicated.

**Pull request closed without merging**
