### PR TITLE
Eval and inject types for input flakes

### PR DESCRIPTION
**Pull request by oxalica**
Part of #14

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
How can I disable this feature? On my editor this also evaluates checks which slows down my machine.

**Comment by getchoo** [comment]
i was just about to ask the same. i looked through the docs, but couldn't find anything related to it :(

**Comment by oxalica** [comment]
> How can I disable this feature?

Implemented in https://github.com/oxalica/nil/commit/21d0870aaba406c41acaf602ce59d000fba7a27c

**Comment by SuperSandro2000** [comment]
Thanks!

**Comment by dschrempf** [comment]
Hi! Could you please create a release including the mentioned configuration option? I can not use `nil` anymore because my computer always runs out of memory. Thank you!

**Comment by oxalica** [comment]
> Hi! Could you please create a release including the mentioned configuration option? I can not use `nil` anymore because my computer always runs out of memory. Thank you!

https://github.com/oxalica/nil/releases/tag/2023-05-09

**Pull request merged**
